AWSTemplateFormatVersion: "2010-09-09"

Description: "AWS CloudFormation Sample Template RDS_PIOPS: Sample template showing how to create an Amazon RDS Database Instance with provisioned IOPs.**WARNING** This template creates an Amazon Relational Database Service database instance. You will be billed for the AWS resources used if you create a stack from this template."

Metadata:
  License: Apache-2.0

Parameters:
  DBUser:
    Description: The database admin account username
    Type: String
    Default: admin
  DBPassword:
    Description: Database Password
    Type: String
    Default: Welcome#1987
  PrivateSubnet01:
    Description: Pvt Subnet1
    Type: String
    Default: subnet-06fd06e080409734c
  PrivateSubnet02:
    Description: Pvt Subnet2
    Type: String
    Default: subnet-0a8fd0ccbc5a3a350

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS instance"
      SubnetIds:
        - !Ref PrivateSubnet01
        - !Ref PrivateSubnet02
      DBSubnetGroupName: MySubnetGroup
  myDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: db.t3.micro
      BackupRetentionPeriod: 7
      Engine: MySQL
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      StorageEncrypted: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBName: registration
